@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.5.0
rem  Generated on: 2026-07-31 11:16
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=MWGA - Make Windows Great Again"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgUnVubmVyDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My41LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTMxIDExOjE2DQpyZW0NCnJlbSAgRU5UUllfTU9ERToNCnJlbSAgICBmaWxlICAgLT4gcHl0
        echo aG9uIGFwcC5weQ0KcmVtICAgIG1vZHVsZSAtPiBweXRob24gLW0gcGFja2FnZS5tb2R1bGUNCnJl
        echo bSAgICBydW5uZXIgLT4gcHl0aG9uIC1tIHJ1bm5lcl9tb2R1bGUgW2FyZ3MuLi5dDQpyZW0gICAg
        echo c2NyaXB0IC0+IHZlbnYgU2NyaXB0c1xhcHAuZXhlIFthcmdzLi4uXSAgIChjb25zb2xlIHNjcmlw
        echo dCkNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9TVdHQSAtIE1ha2UgV2luZG93cyBHcmVh
        echo dCBBZ2FpbiINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNl
        echo dCAiQVBQX0VOVFJZPW13Z2FfcGFuZWwucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCg0Kc2V0ICJQ
        echo WT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0Kc2V0ICJTQ1JJUFRfRVhFPSVD
        echo RCVcJVZFTlZfRElSJVxTY3JpcHRzXCVBUFBfRU5UUlklLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIl
        echo UFklIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAg
        echo ICBlY2hvLg0KICAgIGVjaG8gRml4IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIl
        echo VkVOVl9ESVIlIg0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiIC1t
        echo IHBpcCBpbnN0YWxsIC0tdXBncmFkZSBwaXANCiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2NyaXB0
        echo c1xweXRob24uZXhlIiAtbSBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNo
        echo by4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQppZiAvSSAiJUVOVFJZX01PREUlIj09
        echo ImZpbGUiIGlmIG5vdCBleGlzdCAiJUFQUF9FTlRSWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gRW50
        echo cnkgZmlsZSBub3QgZm91bmQ6ICIlQVBQX0VOVFJZJSINCiAgICBlY2hvIEVkaXQgcnVuLmJhdCBv
        echo ciBydW4gd2l0aCB0aGUgY29ycmVjdCBlbnRyeSBmaWxlLg0KICAgIHBhdXNlDQogICAgZXhpdCAv
        echo YiAxDQopDQoNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0ic2NyaXB0IiBpZiBub3QgZXhpc3QgIiVT
        echo Q1JJUFRfRVhFJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBDb25zb2xlIHNjcmlwdCBub3QgZm91bmQ6
        echo ICIlU0NSSVBUX0VYRSUiDQogICAgZWNoby4NCiAgICBlY2hvIFRoZSB2ZW52IGV4aXN0cyBidXQg
        echo ZG9lcyBub3QgcHJvdmlkZSB0aGlzIHNjcmlwdC4gRml4IHdpdGg6DQogICAgZWNobyAgIHBpcC5i
        echo YXQgaW5zdGFsbCAtZSAuDQogICAgZWNobyBvciBpbnN0YWxsIHRoZSBwYWNrYWdlIHRoYXQgcHJv
        echo dmlkZXMgIiVBUFBfRU5UUlklIi4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRs
        echo ZSAiJVBST0pFQ1RfTkFNRSUgLSBSVU4iDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUnVubmluZyA6ICVQUk9K
        echo RUNUX05BTUUlDQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNobyAgUHl0aG9uICA6ICVQWSUNCmVj
        echo aG8gIE1vZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVudHJ5ICAgOiAlQVBQX0VOVFJZJQ0K
        echo aWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gIEFyZ3MgICAgOiAiJVJVTk5FUl9B
        echo UkdTJSINCmlmIC9JICIlRU5UUllfTU9ERSUiPT0ic2NyaXB0IiBlY2hvICBBcmdzICAgIDogIiVS
        echo VU5ORVJfQVJHUyUiDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0Kc2V0ICJFWElUQ09ERT0wIg0KDQppZiAv
        echo SSAiJUVOVFJZX01PREUlIj09Im1vZHVsZSIgKA0KICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAl
        echo Kg0KKSBlbHNlIGlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiAoDQogICAgIiVQWSUiIC1t
        echo ICVBUFBfRU5UUlklICUqDQopIGVsc2UgaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJzY3JpcHQiICgN
        echo CiAgICAiJVNDUklQVF9FWEUlIiAlKg0KKSBlbHNlICgNCiAgICAiJVBZJSIgIiVBUFBfRU5UUlkl
        echo IiAlKg0KKQ0KDQpzZXQgIkVYSVRDT0RFPSVFUlJPUkxFVkVMJSINCg0KZWNoby4NCmVjaG8gPT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo DQplY2hvICBQcm9jZXNzIGV4aXRlZCB3aXRoIGNvZGU6ICVFWElUQ09ERSUNCmVjaG8gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpw
        echo YXVzZQ0KZXhpdCAvYiAlRVhJVENPREUlDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjUuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMzEgMTE6MTYNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My41LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTMx
        echo IDExOjE2DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9TVdHQSAtIE1ha2UgV2luZG93cyBHcmVhdCBBZ2FpbiINCnNldCAiVkVOVl9ESVI9LnZl
        echo bnYiDQpzZXQgIkFDVElWQVRFPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXGFjdGl2YXRlLmJhdCIN
        echo Cg0KaWYgbm90IGV4aXN0ICIlQUNUSVZBVEUlIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZl
        echo bnYgd2FzIG5vdCBmb3VuZDoNCiAgICBlY2hvICAgICAgICAgIiVBQ1RJVkFURSUiDQogICAgZWNo
        echo by4NCiAgICBlY2hvIENyZWF0ZSBpdCB3aXRoOg0KICAgIGVjaG8gICAgICAgICBweXRob24gLW0g
        echo dmVudiAiJVZFTlZfRElSJSINCiAgICBlY2hvLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQop
        echo DQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFZFTlYgU0hFTEwiDQpjYWxsICIlQUNUSVZBVEUl
        echo Ig0KDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PQ0KZWNobyAgUHJvamVjdCBzaGVsbCBhY3RpdmF0ZWQNCmVjaG8gIFByb2pl
        echo Y3Q6ICIlQ0QlIg0KZWNobyAgUHl0aG9uIDoNCndoZXJlIHB5dGhvbg0KZWNobyAgVHlwZSAiZXhp
        echo dCIgdG8gbGVhdmUgdGhpcyBzaGVsbC4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvLg0KY21kIC9rDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNS4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0zMSAxMToxNg0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1NV0dBIC0g
        echo TWFrZSBXaW5kb3dzIEdyZWF0IEFnYWluIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiUFk9
        echo JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFkl
        echo IiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAgICBl
        echo Y2hvLg0KICAgIGVjaG8gQ3JlYXRlIGl0IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52
        echo ICIlVkVOVl9ESVIlIg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJP
        echo SkVDVF9OQU1FJSAtIFNZTkMiDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBTeW5jaW5nOiAlUFJPSkVDVF9O
        echo QU1FJQ0KZWNobyAgUHl0aG9uIDogJVBZJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQoNCmVjaG8gWzEvM10g
        echo VXBncmFkaW5nIHBpcC4uLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT0NCiIlUFklIiAtbSBwaXAgaW5zdGFsbCAtLXVwZ3Jh
        echo ZGUgcGlwDQplY2hvLg0KDQppZiBleGlzdCAicmVxdWlyZW1lbnRzLnR4dCIgKA0KICAgIGVjaG8g
        echo WzIvM10gSW5zdGFsbGluZyBmcm9tIHJlcXVpcmVtZW50cy50eHQuLi4NCiAgICBlY2hvID09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0K
        echo ICAgICIlUFklIiAtbSBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4N
        echo CikgZWxzZSAoDQogICAgZWNobyBbMi8zXSBTS0lQUEVEOiBObyByZXF1aXJlbWVudHMudHh0IGZv
        echo dW5kLg0KICAgIGVjaG8gICAgICAgQ3JlYXRlIG9uZSB3aXRoOiBwaXAuYmF0IGZyZWV6ZSBePiBy
        echo ZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4NCikNCg0KZWNobyBbMy8zXSBEZXBlbmRlbmN5IGhl
        echo YWx0aCBjaGVjay4uLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVj
        echo aG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09DQplY2hvICBTWU5DIENPTVBMRVRFDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My41LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTMxIDExOjE2DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPU1XR0EgLSBNYWtlIFdp
        echo bmRvd3MgR3JlYXQgQWdhaW4iDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RF
        echo PWZpbGUiDQpzZXQgIkFQUF9FTlRSWT1td2dhX3BhbmVsLnB5Ig0Kc2V0ICJSVU5ORVJfQVJHUz0i
        echo DQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmVjaG8gPT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo DQplY2hvICBQUk9KRUNUIERPQ1RPUjogJVBST0pFQ1RfTkFNRSUNCmVjaG8gPT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQ
        echo cm9qZWN0IDogJUNEJQ0KZWNobyAgTW9kZSAgICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkg
        echo ICA6ICVBUFBfRU5UUlklDQppZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJn
        echo cyAgICA6ICIlUlVOTkVSX0FSR1MlIg0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJzY3JpcHQiIGVj
        echo aG8gIEFyZ3MgICAgOiAiJVJVTk5FUl9BUkdTJSINCmVjaG8uDQoNCmlmIG5vdCBleGlzdCAiJVBZ
        echo JSIgKA0KICAgIGVjaG8gW0ZBSUxdIHZlbnYgbm90IGZvdW5kIGF0OiAiJVBZJSINCiAgICBlY2hv
        echo Lg0KICAgIGVjaG8gQ3JlYXRlIGl0IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIl
        echo VkVOVl9ESVIlIg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCmVjaG8gW09LXSB2ZW52
        echo IGZvdW5kOiAiJVBZJSINCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeXRob24gRW52aXJvbm1l
        echo bnQNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImltcG9ydCBzeXM7IHByaW50KCdFeGVjdXRhYmxlIDon
        echo LCBzeXMuZXhlY3V0YWJsZSk7IHByaW50KCdWZXJzaW9uICAgIDonLCBzeXMudmVyc2lvbi5zcGxp
        echo dCgpWzBdKTsgcHJpbnQoJ1ByZWZpeCAgICAgOicsIHN5cy5wcmVmaXgpIg0KZWNoby4NCg0KZWNo
        echo byAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0NCmVjaG8gIHBpcCB2ZXJzaW9uDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBpcCAtLXZlcnNp
        echo b24NCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBJbnN0YWxsZWQgUGFja2FnZXMNCmVjaG8gLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo DQoiJVBZJSIgLW0gcGlwIGxpc3QNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBEZXBlbmRlbmN5
        echo IEhlYWx0aA0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo DQplY2hvICBFbnRyeSBQb2ludCBDaGVjaw0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmlmIC9JICIlRU5UUllfTU9ERSUi
        echo PT0iZmlsZSIgKA0KICAgIGlmIGV4aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgICAgICBlY2hvIFtP
        echo S10gRW50cnkgZmlsZSBmb3VuZDogIiVBUFBfRU5UUlklIg0KICAgICkgZWxzZSAoDQogICAgICAg
        echo IGVjaG8gW0ZBSUxdIEVudHJ5IGZpbGUgTk9UIGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgKQ0K
        echo KSBlbHNlIGlmIC9JICIlRU5UUllfTU9ERSUiPT0ic2NyaXB0IiAoDQogICAgaWYgZXhpc3QgIiVD
        echo RCVcJVZFTlZfRElSJVxTY3JpcHRzXCVBUFBfRU5UUlklLmV4ZSIgKA0KICAgICAgICBlY2hvIFtP
        echo S10gQ29uc29sZSBzY3JpcHQgZm91bmQ6ICIlQVBQX0VOVFJZJS5leGUiDQogICAgKSBlbHNlICgN
        echo CiAgICAgICAgZWNobyBbRkFJTF0gQ29uc29sZSBzY3JpcHQgTk9UIGZvdW5kOiAiJUNEJVwlVkVO
        echo Vl9ESVIlXFNjcmlwdHNcJUFQUF9FTlRSWSUuZXhlIg0KICAgICAgICBlY2hvICAgICAgICBGaXgg
        echo d2l0aDogcGlwLmJhdCBpbnN0YWxsIC1lIC4NCiAgICApDQogICAgaWYgZGVmaW5lZCBSVU5ORVJf
        echo QVJHUyBlY2hvIFtJTkZPXSBSdW5uZXIgYXJnczogIiVSVU5ORVJfQVJHUyUiDQopIGVsc2UgKA0K
        echo ICAgICIlUFklIiAtYyAiaW1wb3J0IGltcG9ydGxpYi51dGlsLCBzeXM7IG5hbWU9ciclQVBQX0VO
        echo VFJZJSc7IHNwZWM9aW1wb3J0bGliLnV0aWwuZmluZF9zcGVjKG5hbWUpOyBwcmludCgoJ1tPS10g
        echo TW9kdWxlIGZvdW5kOiAnIGlmIHNwZWMgZWxzZSAnW0ZBSUxdIE1vZHVsZSBOT1QgZm91bmQ6ICcp
        echo ICsgbmFtZSk7IHN5cy5leGl0KDAgaWYgc3BlYyBlbHNlIDEpIiAyPm51bA0KICAgIGlmIGVycm9y
        echo bGV2ZWwgMSBlY2hvIFtGQUlMXSBNb2R1bGUgaW1wb3J0IHRlc3QgZmFpbGVkLg0KICAgIGlmIC9J
        echo ICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvIFtJTkZPXSBSdW5uZXIgYXJnczogIiVSVU5O
        echo RVJfQVJHUyUiDQopDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgUHJvamVjdCBGaWxlcw0KZWNo
        echo byAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0NCmlmIGV4aXN0ICJ1di5sb2NrIiAgICAgICAgICBlY2hvIFtPS10gICB1di5sb2NrIGZv
        echo dW5kDQppZiBleGlzdCAicHlwcm9qZWN0LnRvbWwiICAgZWNobyBbT0tdICAgcHlwcm9qZWN0LnRv
        echo bWwgZm91bmQNCmlmIGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtPS10gICByZXF1aXJl
        echo bWVudHMudHh0IGZvdW5kDQppZiBub3QgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiIGVjaG8gW1dB
        echo Uk5dIHJlcXVpcmVtZW50cy50eHQgbWlzc2luZw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIERP
        echo Q1RPUiBDT01QTEVURQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjUuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMzEgMTE6MTYNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1NV0dBIC0gTWFrZSBXaW5kb3dzIEdyZWF0IEFn
        echo YWluIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlw
        echo dHNccHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRVJST1Jd
        echo IExvY2FsIHZlbnYgd2FzIG5vdCBmb3VuZDoNCiAgICBlY2hvICAgICAgICAgIiVQWSUiDQogICAg
        echo ZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFN
        echo RSUgLSBURVNUIg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFRlc3Rpbmc6ICIlUFJPSkVDVF9OQU1FJSINCmVj
        echo aG8gIFB5dGhvbiA6ICIlUFklIg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8uDQoiJVBZJSIgLW0gcHl0ZXN0IC12
        echo ICUqDQpzZXQgIkVYSVRDT0RFPSVFUlJPUkxFVkVMJSINCg0KZWNoby4NCmVjaG8gPT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQppZiAi
        echo JUVYSVRDT0RFJSI9PSIwIiAoDQogICAgZWNobyAgVEVTVFMgUEFTU0VEDQopIGVsc2UgKA0KICAg
        echo IGVjaG8gIFRFU1RTIEZBSUxFRCAgXihleGl0IGNvZGU6ICVFWElUQ09ERSVeKQ0KKQ0KZWNobyA9
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT0NCnBhdXNlDQpleGl0IC9iICVFWElUQ09ERSUNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
